spring.application.name=mrMoferBackend

spring.datasource.url=jdbc:mysql://localhost:3306/mrmoferbdd
spring.datasource.username=root
spring.datasource.password=root

JPA / Hibernate,
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
